apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    all: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app